# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RepoContext < Formula
  desc "Smart file selection for LLMs"
  homepage "https://github.com/demwunz/wobot"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/demwunz/wobot/releases/download/v0.9.0/repo-context_0.9.0_darwin_amd64.tar.gz"
      sha256 "69fee0110497ef118eb89faf6f842e3cb765682f7baff4089cfc19549d02c8f5"

      def install
        bin.install "repo-context"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/demwunz/wobot/releases/download/v0.9.0/repo-context_0.9.0_darwin_arm64.tar.gz"
      sha256 "d66d31a5abcf3e23a6b4e308cc007a5fa97292aef911a9f517042275843deb14"

      def install
        bin.install "repo-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/demwunz/wobot/releases/download/v0.9.0/repo-context_0.9.0_linux_amd64.tar.gz"
      sha256 "8dcbf173c85597fb5e92e85b331f4337b8e5834655557fc8f7434a5c9ec026f8"
      def install
        bin.install "repo-context"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/demwunz/wobot/releases/download/v0.9.0/repo-context_0.9.0_linux_arm64.tar.gz"
      sha256 "b1290b4a2c2f66eb79ae94eae7bd95cb6ced9807d0b5f12f72d868402e0352b3"
      def install
        bin.install "repo-context"
      end
    end
  end

  test do
    system "#{bin}/repo-context", "--version"
  end
end
